export const APP_JS = `
const SESSION_KEY='blobforge_session';
const fragment=new URLSearchParams(location.hash.slice(1));
const fragmentSession=fragment.get('session');
if(fragmentSession){localStorage.setItem(SESSION_KEY,fragmentSession);history.replaceState(null,'',location.pathname+location.search)}
const sessionToken=localStorage.getItem(SESSION_KEY)||'';
let snapshot={jobs:[],workers:[],worker_enrollments:[],counts:{},config:{}};
const $=selector=>document.querySelector(selector);
const age=timestamp=>{if(!timestamp)return '—';const seconds=Math.max(0,Math.floor((Date.now()-timestamp)/1000));if(seconds<60)return seconds+'s ago';if(seconds<3600)return Math.floor(seconds/60)+'m ago';if(seconds<86400)return Math.floor(seconds/3600)+'h ago';return Math.floor(seconds/86400)+'d ago'};
function toast(message){const element=$('#toast');element.textContent=message;element.classList.add('show');setTimeout(()=>element.classList.remove('show'),2500)}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'content-type':'application/json','authorization':'BlobForge-Session '+sessionToken,...(options.headers||{})}});if(response.status===401){localStorage.removeItem(SESSION_KEY);location.replace('/');throw new Error('Session expired')}const body=response.status===204?null:await response.json();if(!response.ok)throw new Error(body?.error||'Request failed');return body}
function renderWorkers(){const container=$('#workers');const enrollments=snapshot.worker_enrollments||[];container.replaceChildren(...enrollments.map(worker=>{const card=document.createElement('article');card.className='worker';const top=document.createElement('div');top.className='worker-top';const name=document.createElement('strong');name.textContent=worker.label||worker.hostname||worker.worker_id;const state=worker.revoked_at?'revoked':worker.status;const status=document.createElement('span');const dot=document.createElement('i');dot.className='dot '+state;status.append(dot,document.createTextNode(state));top.append(name,status);const identity=document.createElement('p');identity.textContent=worker.worker_id;const activity=document.createElement('p');activity.textContent=(worker.current_job?'Job '+worker.current_job.slice(0,12):worker.hostname||'Not connected')+' · '+age(worker.last_heartbeat||worker.last_used_at);card.append(top,identity,activity);if(!worker.revoked_at){const revoke=document.createElement('button');revoke.type='button';revoke.className='danger';revoke.textContent='Revoke';revoke.onclick=async()=>{if(!confirm('Revoke '+(worker.label||worker.worker_id)+'? Its active lease will be requeued.'))return;try{await api('/api/v1/admin/workers/'+encodeURIComponent(worker.worker_id)+'/revoke',{method:'POST',body:'{}'});toast('Worker revoked');await load()}catch(error){toast(error.message)}};card.append(revoke)}return card}))}
function renderJobs(){const filter=$('#status-filter').value;const query=$('#search').value.toLowerCase();const jobs=snapshot.jobs.filter(job=>(!filter||job.status===filter)&&(!query||job.hash.includes(query)||(job.original_name||'').toLowerCase().includes(query)));const body=$('#jobs');body.replaceChildren(...jobs.map(job=>{const row=document.createElement('tr');const identity=document.createElement('td');const name=document.createElement('div');name.className='job-name';name.textContent=job.original_name||'Unknown PDF';const hash=document.createElement('div');hash.className='hash';hash.textContent=job.hash;identity.append(name,hash);const state=document.createElement('td');const badge=document.createElement('span');badge.className='badge '+job.status;badge.textContent=job.status+(job.retry_count?' · '+job.retry_count:'');state.append(badge);const priority=document.createElement('td');const select=document.createElement('select');['1_critical','2_high','3_normal','4_low','5_background'].forEach(value=>{const option=document.createElement('option');option.value=value;option.textContent=value.replace(/^\\d_/,'');option.selected=value===job.priority;select.append(option)});select.disabled=!['todo','failed'].includes(job.status);select.onchange=()=>jobAction(job.hash,'priority',{priority:select.value});priority.append(select);const progress=document.createElement('td');progress.textContent=job.worker_id||job.progress?.stage||'—';const updated=document.createElement('td');updated.textContent=age(job.updated_at);const actions=document.createElement('td');actions.className='actions';if(['failed','dead'].includes(job.status)){const retry=document.createElement('button');retry.textContent='Retry';retry.onclick=()=>jobAction(job.hash,'retry');actions.append(retry)}if(job.status==='processing'){const cancel=document.createElement('button');cancel.className='quiet';cancel.textContent='Cancel';cancel.onclick=()=>jobAction(job.hash,'cancel');actions.append(cancel)}row.append(identity,state,priority,progress,updated,actions);return row}))}
function render(){const account=$('.account span');if(account)account.textContent=snapshot.identity||'';const states=['todo','processing','failed','dead','done'];$('#stats').replaceChildren(...states.map(state=>{const element=document.createElement('div');element.className='stat';const count=document.createElement('strong');count.textContent=snapshot.counts[state]||0;const label=document.createElement('span');label.textContent=state;element.append(count,label);return element}));renderWorkers();renderJobs();for(const [key,value] of Object.entries(snapshot.config))if($('#config-form').elements[key])$('#config-form').elements[key].value=value}
async function load(){snapshot=await api('/api/v1/admin/snapshot');render()}
async function jobAction(hash,name,body={}){try{await api('/api/v1/admin/jobs/'+hash+'/'+name,{method:'POST',body:JSON.stringify(body)});toast(name+' complete');await load()}catch(error){toast(error.message)}}
$('#signout').onclick=()=>{localStorage.removeItem(SESSION_KEY);location.replace('/')};
$('#status-filter').onchange=renderJobs;
$('#search').oninput=renderJobs;
$('#new-worker').onclick=()=>{$('#worker-form').hidden=false;$('#worker-credential').hidden=true;$('#worker-form').elements.label.focus()};
$('#cancel-worker').onclick=()=>{$('#worker-form').hidden=true};
$('#worker-form').onsubmit=async event=>{event.preventDefault();const label=String(new FormData(event.target).get('label')||'').trim();try{const enrollment=await api('/api/v1/admin/workers',{method:'POST',body:JSON.stringify({label})});const command='blobforge worker --coordinator-url '+enrollment.coordinator_url+' --token '+enrollment.token;$('#worker-command').textContent=command;$('#worker-credential').hidden=false;event.target.hidden=true;event.target.reset();toast('Worker created');await load()}catch(error){toast(error.message)}};
$('#copy-worker').onclick=async()=>{try{await navigator.clipboard.writeText($('#worker-command').textContent);toast('Command copied')}catch(error){toast('Could not copy command')}};
$('#recover').onclick=async()=>{try{const result=await api('/api/v1/admin/recover',{method:'POST',body:'{}'});toast('Recovered '+result.recovered+' lease(s)');await load()}catch(error){toast(error.message)}};
$('#backup').onclick=async()=>{const button=$('#backup');button.disabled=true;try{const result=await api('/api/v1/admin/backups',{method:'POST',body:'{}'});toast('Backup saved: '+result.key)}catch(error){toast(error.message)}finally{button.disabled=false}};
$('#config-form').onsubmit=async event=>{event.preventDefault();const data=Object.fromEntries([...new FormData(event.target)].map(([key,value])=>[key,Number(value)]));try{await api('/api/v1/admin/config',{method:'PUT',body:JSON.stringify(data)});toast('Configuration saved');await load()}catch(error){toast(error.message)}};
load();setInterval(load,30000);`;
