export const APP_JS = `
const SESSION_KEY='blobforge_session';
const fragment=new URLSearchParams(location.hash.slice(1));const fragmentSession=fragment.get('session');
if(fragmentSession){localStorage.setItem(SESSION_KEY,fragmentSession);history.replaceState(null,'',location.pathname+location.search)}
const sessionToken=localStorage.getItem(SESSION_KEY)||'';const PAGE_SIZE=50;
let snapshot={workers:[],worker_enrollments:[],counts:{},config:{}},filePage={jobs:[],total:0},offset=0,searchTimer,viewerUrls=[],tocScrollHandler;
const $=selector=>document.querySelector(selector);
const age=timestamp=>{if(!timestamp)return '—';const seconds=Math.max(0,Math.floor((Date.now()-timestamp)/1000));if(seconds<60)return seconds+'s ago';if(seconds<3600)return Math.floor(seconds/60)+'m ago';if(seconds<86400)return Math.floor(seconds/3600)+'h ago';return Math.floor(seconds/86400)+'d ago'};
const size=bytes=>{let value=Number(bytes||0);if(!value)return '—';const units=['B','KB','MB','GB'];let unit=0;while(value>=1024&&unit<units.length-1){value/=1024;unit++}return value.toFixed(unit?1:0)+' '+units[unit]};
function toast(message){const element=$('#toast');element.textContent=message;element.classList.add('show');setTimeout(()=>element.classList.remove('show'),3500)}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'content-type':'application/json','authorization':'BlobForge-Session '+sessionToken,...(options.headers||{})}});if(response.status===401){localStorage.removeItem(SESSION_KEY);location.replace('/login');throw new Error('Session expired')}const body=response.status===204?null:await response.json();if(!response.ok)throw new Error(body?.error||'Request failed');return body}
function workerCard(worker,revoked=false){const card=document.createElement('article');card.className='worker';const top=document.createElement('div');top.className='worker-top';const name=document.createElement('strong');name.textContent=worker.label||worker.hostname||worker.worker_id;const state=revoked?'revoked':worker.status;const status=document.createElement('span');const dot=document.createElement('i');dot.className='dot '+state;status.append(dot,document.createTextNode(state));top.append(name,status);const identity=document.createElement('p');identity.textContent=worker.worker_id;const suspendedUntil=state==='suspended'&&worker.state?.until?new Date(worker.state.until).toLocaleString():null;const activity=document.createElement('p');activity.textContent=suspendedUntil?'Suspended until '+suspendedUntil:(worker.current_job?'Job '+worker.current_job.slice(0,12):worker.hostname||'Not connected')+' · '+age(worker.last_heartbeat||worker.last_used_at);card.append(top,identity,activity);if(!revoked){const revoke=document.createElement('button');revoke.type='button';revoke.className='danger';revoke.textContent='Revoke';revoke.onclick=async()=>{if(!confirm('Revoke '+(worker.label||worker.worker_id)+'? Its active lease will be requeued.'))return;try{await api('/api/v1/admin/workers/'+encodeURIComponent(worker.worker_id)+'/revoke',{method:'POST',body:'{}'});toast('Worker revoked');await loadSnapshot()}catch(error){toast(error.message)}};card.append(revoke)}return card}
function renderWorkers(){const container=$('#workers');container.replaceChildren(...(snapshot.worker_enrollments||[]).map(worker=>workerCard(worker)))}
function actionButton(label,handler,className='quiet'){const button=document.createElement('button');button.type='button';button.textContent=label;button.className=className;button.onclick=handler;return button}
async function transfer(hash,kind){return api('/api/v1/admin/files/'+hash+'/download?kind='+kind)}
async function download(job,kind){try{const result=await transfer(job.hash,kind);const link=document.createElement('a');link.href=result.url;link.download=kind==='raw'?(job.original_name||job.hash+'.pdf'):(job.original_name||job.hash).replace(/\.pdf$/i,'')+'.zip';document.body.append(link);link.click();link.remove()}catch(error){toast(error.message)}}
function progressCell(job){const cell=document.createElement('td');if(['failed','dead'].includes(job.status)){const summary=document.createElement('div');summary.className='failure-summary';const stage=job.latest_failure_context?.stage;summary.textContent=(stage?stage+': ':'')+(job.error_message||'Unknown failure');cell.append(summary);return cell}if(job.status!=='processing'){cell.textContent=job.progress?.stage||'—';return cell}cell.className='job-progress';const marker=job.progress?.marker||{},markerPercent=Number(marker.tqdm_percent);const estimated=job.progress?.stage==='converting'&&Number.isFinite(markerPercent)?15+markerPercent*.7:Number(job.progress?.percent??0);const percent=Math.max(0,Math.min(100,estimated));const label=document.createElement('div');label.className='progress-label';const stage=document.createElement('strong');stage.textContent=marker.tqdm_stage||job.progress?.stage||'processing';const value=document.createElement('span');value.textContent=Math.round(percent)+'%';label.append(stage,value);const track=document.createElement('div');track.className='progress-track';const fill=document.createElement('i');fill.style.width=percent+'%';track.append(fill);const detail=document.createElement('div');detail.className='progress-detail';detail.textContent=[job.worker_id,marker.tqdm_total?marker.tqdm_current+'/'+marker.tqdm_total:null,marker.tqdm_eta?'ETA '+Math.ceil(marker.tqdm_eta)+'s':null,job.progress?.elapsed_formatted].filter(Boolean).join(' · ');cell.append(label,track,detail);return cell}
function definition(term,value){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=term;dd.textContent=value??'—';return [dt,dd]}
async function showFailures(job){const dialog=$('#failure-viewer'),body=$('#failure-body');$('#failure-title').textContent=job.original_name||job.hash;body.textContent='Loading failure history…';dialog.showModal();try{const result=await api('/api/v1/admin/jobs/'+job.hash+'/failures');if(!result.failures.length){body.textContent='No structured failure records are available for this job.';return}body.replaceChildren(...result.failures.map(failure=>{const entry=document.createElement('article');entry.className='failure-entry';const title=document.createElement('h3');title.textContent=failure.error_message;const facts=document.createElement('dl');facts.append(...definition('Attempt',String(failure.attempt)),...definition('When',new Date(failure.failed_at).toLocaleString()),...definition('Worker',failure.worker_id),...definition('Stage',failure.context?.stage),...definition('Type',failure.context?.exception_type));entry.append(title,facts);const diagnostics={context:failure.context,progress:failure.progress};const details=document.createElement('details');const summary=document.createElement('summary');summary.textContent='Diagnostics';const pre=document.createElement('pre');pre.textContent=JSON.stringify(diagnostics,null,2);details.append(summary,pre);entry.append(details);if(failure.traceback){const trace=document.createElement('details');const traceSummary=document.createElement('summary');traceSummary.textContent='Traceback';const traceBody=document.createElement('pre');traceBody.textContent=failure.traceback;trace.append(traceSummary,traceBody);entry.append(trace)}return entry}))}catch(error){body.textContent=error.message}}
function renderJobs(){const body=$('#jobs');body.replaceChildren(...filePage.jobs.map(job=>{const row=document.createElement('tr');const identity=document.createElement('td');const name=document.createElement('div');name.className='job-name';name.textContent=job.original_name||'Unknown PDF';const hash=document.createElement('div');hash.className='hash';hash.textContent=job.hash;const meta=document.createElement('div');meta.className='file-meta';meta.textContent=[size(job.size_bytes),(job.tags||[]).slice(0,4).join(', '),(job.paths||[])[0]].filter(Boolean).join(' · ');identity.append(name,hash,meta);const state=document.createElement('td');const badge=document.createElement('span');badge.className='badge '+job.status;badge.textContent=job.status+(job.retry_count?' · '+job.retry_count:'');state.append(badge);const priority=document.createElement('td');const select=document.createElement('select');['1_critical','2_high','3_normal','4_low','5_background'].forEach(value=>{const option=document.createElement('option');option.value=value;option.textContent=value.replace(/^\\d_/,'');option.selected=value===job.priority;select.append(option)});select.disabled=!['todo','failed'].includes(job.status);select.onchange=()=>jobAction(job.hash,'priority',{priority:select.value});priority.append(select);const progress=progressCell(job);const updated=document.createElement('td');updated.textContent=age(job.updated_at);const actions=document.createElement('td');actions.className='actions';actions.append(actionButton('PDF',()=>download(job,'raw')));if(job.status==='done'){actions.append(actionButton('ZIP',()=>download(job,'output')));actions.append(actionButton('View',()=>preview(job),'button'))}if(job.retry_count||['failed','dead'].includes(job.status))actions.append(actionButton('Failures',()=>showFailures(job)));if(['failed','dead'].includes(job.status))actions.append(actionButton('Retry',()=>jobAction(job.hash,'retry'),'button'));if(job.status==='processing')actions.append(actionButton('Cancel',()=>jobAction(job.hash,'cancel')));row.append(identity,state,priority,progress,updated,actions);return row}));const start=filePage.total?offset+1:0;const end=Math.min(offset+PAGE_SIZE,filePage.total);$('#result-count').textContent=filePage.total+' result'+(filePage.total===1?'':'s');$('#page-label').textContent=start+'–'+end+' of '+filePage.total;$('#prev-page').disabled=offset===0;$('#next-page').disabled=offset+PAGE_SIZE>=filePage.total}
function renderSnapshot(){const account=$('.account span');if(account)account.textContent=snapshot.identity||'';const states=['todo','processing','failed','dead','done'];$('#stats').replaceChildren(...states.map(state=>{const element=document.createElement('div');element.className='stat';const count=document.createElement('strong');count.textContent=snapshot.counts[state]||0;const label=document.createElement('span');label.textContent=state;element.append(count,label);return element}));renderWorkers();for(const [key,value] of Object.entries(snapshot.config||{})){const input=$('#config-form').elements[key];if(!input)continue;if(input.type==='checkbox')input.checked=Boolean(value);else input.value=value}}
async function loadSnapshot(){snapshot=await api('/api/v1/admin/snapshot');renderSnapshot()}
async function loadFiles(){const params=new URLSearchParams({limit:String(PAGE_SIZE),offset:String(offset)});const query=$('#search').value.trim(),status=$('#status-filter').value,priority=$('#priority-filter').value;if(query)params.set('q',query);if(status)params.set('status',status);if(priority)params.set('priority',priority);filePage=await api('/api/v1/admin/files?'+params);renderJobs()}
async function load(){await Promise.all([loadSnapshot(),loadFiles()])}
async function jobAction(hash,name,body={}){try{await api('/api/v1/admin/jobs/'+hash+'/'+name,{method:'POST',body:JSON.stringify(body)});toast(name+' complete');await load()}catch(error){toast(error.message)}}
async function hashFile(file){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
async function uploadFiles(files){const status=$('#upload-status');status.hidden=false;for(let index=0;index<files.length;index++){const file=files[index];try{if(!file.name.toLowerCase().endsWith('.pdf')||await file.slice(0,5).text()!=='%PDF-')throw new Error('Not a valid PDF');status.textContent='Hashing '+file.name+' ('+(index+1)+'/'+files.length+')…';const hash=await hashFile(file);status.textContent='Preparing '+file.name+'…';const prepared=await api('/api/v1/admin/uploads',{method:'POST',body:JSON.stringify({hash})});if(!prepared.already_exists){status.textContent='Uploading '+file.name+' ('+size(file.size)+')…';const response=await fetch(prepared.url,{method:'PUT',headers:prepared.headers,body:file});if(!response.ok)throw new Error('Object upload failed ('+response.status+')')}status.textContent='Adding '+file.name+' to the queue…';await api('/api/v1/admin/uploads/'+hash+'/complete',{method:'POST',body:JSON.stringify({original_name:file.name,path:file.webkitRelativePath||file.name,size_bytes:file.size,priority:'3_normal',tags:[]})});toast('Ingested '+file.name)}catch(error){toast(file.name+': '+error.message)}}status.hidden=true;offset=0;await load()}
function findEocd(bytes){const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);for(let offset=bytes.length-22;offset>=Math.max(0,bytes.length-65557);offset--)if(view.getUint32(offset,true)===0x06054b50)return offset;throw new Error('ZIP directory not found')}
async function inflate(data,method){if(method===0)return data;if(method!==8)throw new Error('Unsupported ZIP compression method '+method);const stream=new Blob([data]).stream().pipeThrough(new DecompressionStream('deflate-raw'));return new Uint8Array(await new Response(stream).arrayBuffer())}
async function readZip(buffer){const bytes=new Uint8Array(buffer),view=new DataView(buffer),decoder=new TextDecoder(),eocd=findEocd(bytes),count=view.getUint16(eocd+10,true);if(count>10000)throw new Error('ZIP contains too many files');let cursor=view.getUint32(eocd+16,true),expanded=0;const files=new Map();for(let index=0;index<count;index++){if(view.getUint32(cursor,true)!==0x02014b50)throw new Error('Invalid ZIP directory');const method=view.getUint16(cursor+10,true),compressed=view.getUint32(cursor+20,true),uncompressed=view.getUint32(cursor+24,true),nameLength=view.getUint16(cursor+28,true),extraLength=view.getUint16(cursor+30,true),commentLength=view.getUint16(cursor+32,true),localOffset=view.getUint32(cursor+42,true),name=decoder.decode(bytes.slice(cursor+46,cursor+46+nameLength));expanded+=uncompressed;if(expanded>1073741824)throw new Error('Expanded ZIP is too large to preview safely');const localName=view.getUint16(localOffset+26,true),localExtra=view.getUint16(localOffset+28,true),start=localOffset+30+localName+localExtra;if(!name.endsWith('/'))files.set(name,await inflate(bytes.slice(start,start+compressed),method));cursor+=46+nameLength+extraLength+commentLength}return files}
function mime(path){const ext=path.split('.').pop().toLowerCase();return ({png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',gif:'image/gif',webp:'image/webp',svg:'image/svg+xml'})[ext]||'application/octet-stream'}
function assetUrl(path,files){const clean=path.replace(/^\.\\//,'');const bytes=files.get(clean)||files.get('assets/'+clean.split('/').pop());if(!bytes)return null;const url=URL.createObjectURL(new Blob([bytes],{type:mime(clean)}));viewerUrls.push(url);return url}
function renderToc(headings,body){const container=$('#toc-items'),toc=$('#viewer-toc'),toggle=$('#toc-toggle');container.replaceChildren();toc.hidden=!headings.length;toggle.hidden=!headings.length;const links=new Map();for(const heading of headings){const link=document.createElement('a');link.href='#'+heading.id;link.className='level-'+heading.level;link.textContent=heading.text;link.onclick=event=>{event.preventDefault();body.querySelector('#'+CSS.escape(heading.id))?.scrollIntoView({behavior:'smooth',block:'start'});toc.classList.remove('open');toggle.setAttribute('aria-expanded','false')};links.set(heading.id,link);container.append(link)}tocScrollHandler=()=>{let current=headings[0]?.id;for(const heading of headings){const element=body.querySelector('#'+CSS.escape(heading.id));if(element&&element.offsetTop<=body.scrollTop+50)current=heading.id;else if(element)break}for(const [id,link] of links)link.classList.toggle('active',id===current)};body.onscroll=tocScrollHandler;tocScrollHandler()}
async function preview(job){const viewer=$('#viewer'),body=$('#viewer-body');try{$('#viewer-toc').hidden=true;$('#toc-toggle').hidden=true;body.textContent='Downloading and unpacking result…';$('#viewer-title').textContent=job.original_name||job.hash;viewer.showModal();const result=await transfer(job.hash,'output');const response=await fetch(result.url);if(!response.ok)throw new Error('Could not download ZIP ('+response.status+')');const files=await readZip(await response.arrayBuffer());const markdownKey=[...files.keys()].find(key=>key==='content.md'||key.endsWith('/content.md'));if(!markdownKey)throw new Error('Result has no content.md');const rendered=window.BlobForgeMarkdown.render(new TextDecoder().decode(files.get(markdownKey)),path=>assetUrl(path,files));body.innerHTML=rendered.html;renderToc(rendered.headings,body)}catch(error){body.textContent=error.message+' Check the object-store CORS configuration if the ZIP download was blocked.'}}
$('#signout').onclick=()=>{localStorage.removeItem(SESSION_KEY);location.replace('/')};
$('#new-worker').onclick=()=>{$('#worker-form').hidden=false;$('#worker-credential').hidden=true;$('#worker-form').elements.label.focus()};$('#cancel-worker').onclick=()=>{$('#worker-form').hidden=true};
$('#worker-form').onsubmit=async event=>{event.preventDefault();const label=String(new FormData(event.target).get('label')||'').trim();try{const enrollment=await api('/api/v1/admin/workers',{method:'POST',body:JSON.stringify({label})});const command='curl -fsSLO https://raw.githubusercontent.com/tionis/BlobForge/main/scripts/install-linux-worker.sh\\nchmod +x install-linux-worker.sh\\n./install-linux-worker.sh --coordinator-url '+enrollment.coordinator_url+' --token '+enrollment.token;$('#worker-command').textContent=command;$('#worker-credential').hidden=false;event.target.hidden=true;event.target.reset();toast('Worker created');await loadSnapshot()}catch(error){toast(error.message)}};
$('#copy-worker').onclick=async()=>{try{await navigator.clipboard.writeText($('#worker-command').textContent);toast('Command copied')}catch(error){toast('Could not copy command')}};
$('#show-revoked').onclick=async()=>{const dialog=$('#revoked-viewer'),container=$('#revoked-workers');container.textContent='Loading revoked workers…';dialog.showModal();try{const result=await api('/api/v1/admin/workers?revoked=true');container.replaceChildren(...result.workers.map(worker=>workerCard(worker,true)));if(!result.workers.length)container.textContent='No revoked workers.'}catch(error){container.textContent=error.message}};$('#close-revoked').onclick=()=>$('#revoked-viewer').close();
$('#recover').onclick=async()=>{try{const result=await api('/api/v1/admin/recover',{method:'POST',body:'{}'});toast('Recovered '+result.recovered+' lease(s)');await load()}catch(error){toast(error.message)}};
$('#backup').onclick=async()=>{const button=$('#backup');button.disabled=true;try{const result=await api('/api/v1/admin/backups',{method:'POST',body:'{}'});toast('Backup saved: '+result.key)}catch(error){toast(error.message)}finally{button.disabled=false}};
$('#config-form').onsubmit=async event=>{event.preventDefault();const form=event.target,data={heartbeat_enabled:form.elements.heartbeat_enabled.checked};for(const name of ['heartbeat_interval','lease_seconds','max_retries','conversion_timeout'])data[name]=Number(form.elements[name].value);try{await api('/api/v1/admin/config',{method:'PUT',body:JSON.stringify(data)});toast('Configuration saved');await loadSnapshot()}catch(error){toast(error.message)}};
$('#upload-pdf').onclick=()=>$('#pdf-input').click();$('#pdf-input').onchange=event=>{const files=[...event.target.files];event.target.value='';if(files.length)uploadFiles(files)};
$('#status-filter').onchange=$('#priority-filter').onchange=()=>{offset=0;loadFiles()};$('#search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{offset=0;loadFiles()},250)};
$('#prev-page').onclick=()=>{offset=Math.max(0,offset-PAGE_SIZE);loadFiles()};$('#next-page').onclick=()=>{offset+=PAGE_SIZE;loadFiles()};
$('#toc-toggle').onclick=()=>{const toc=$('#viewer-toc'),open=toc.classList.toggle('open');$('#toc-toggle').setAttribute('aria-expanded',String(open))};$('#close-viewer').onclick=()=>$('#viewer').close();$('#viewer').addEventListener('close',()=>{viewerUrls.forEach(URL.revokeObjectURL);viewerUrls=[];const body=$('#viewer-body');body.onscroll=null;tocScrollHandler=null;body.replaceChildren();$('#toc-items').replaceChildren();$('#viewer-toc').classList.remove('open');$('#toc-toggle').setAttribute('aria-expanded','false')});
$('#close-failures').onclick=()=>$('#failure-viewer').close();
if(sessionToken){load();setInterval(()=>{loadSnapshot();loadFiles()},10000)}else{location.replace('/login')}
`;
